/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`get_blueprint_catalog_service_manifest`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBlueprintCatalogServiceManifestError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status502(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_blueprint_catalog_service_readme`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBlueprintCatalogServiceReadmeError {
    Status400(),
    Status401(),
    Status403(),
    Status404(),
    Status502(),
    UnknownValue(serde_json::Value),
}

/// Returns the list of form fields the console must display to deploy the selected blueprint, derived from the blueprint's qbm.yml manifest. Includes editable variables (overridable=true) and auto-sourced context variables (overridable=false, with a source).
pub async fn get_blueprint_catalog_service_manifest(
    configuration: &configuration::Configuration,
    organization_id: &str,
    provider: &str,
    service_family: &str,
    service_version: &str,
    environment_id: &str,
) -> Result<
    models::GetBlueprintCatalogServiceManifest200Response,
    Error<GetBlueprintCatalogServiceManifestError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_id = organization_id;
    let p_path_provider = provider;
    let p_path_service_family = service_family;
    let p_path_service_version = service_version;
    let p_query_environment_id = environment_id;

    let uri_str = format!("{}/organization/{organizationId}/blueprint/catalog/{provider}/{serviceFamily}/{serviceVersion}/manifest", configuration.base_path, organizationId=crate::apis::urlencode(p_path_organization_id), provider=crate::apis::urlencode(p_path_provider), serviceFamily=crate::apis::urlencode(p_path_service_family), serviceVersion=crate::apis::urlencode(p_path_service_version));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("environmentId", &p_query_environment_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetBlueprintCatalogServiceManifest200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetBlueprintCatalogServiceManifest200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetBlueprintCatalogServiceManifestError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_blueprint_catalog_service_readme(
    configuration: &configuration::Configuration,
    organization_id: &str,
    provider: &str,
    service_family: &str,
    service_version: &str,
) -> Result<models::BlueprintReadmeResponse, Error<GetBlueprintCatalogServiceReadmeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_id = organization_id;
    let p_path_provider = provider;
    let p_path_service_family = service_family;
    let p_path_service_version = service_version;

    let uri_str = format!("{}/organization/{organizationId}/blueprint/catalog/{provider}/{serviceFamily}/{serviceVersion}/readme", configuration.base_path, organizationId=crate::apis::urlencode(p_path_organization_id), provider=crate::apis::urlencode(p_path_provider), serviceFamily=crate::apis::urlencode(p_path_service_family), serviceVersion=crate::apis::urlencode(p_path_service_version));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BlueprintReadmeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BlueprintReadmeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetBlueprintCatalogServiceReadmeError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
