/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgenticWorkflowRunTrigger : What triggered the run. MANUAL is a run started through the deploy endpoint, SCHEDULE a run started by the workflow's cron schedule, WEBHOOK a run started by its webhook.
/// What triggered the run. MANUAL is a run started through the deploy endpoint, SCHEDULE a run started by the workflow's cron schedule, WEBHOOK a run started by its webhook.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgenticWorkflowRunTrigger {
    #[serde(rename = "MANUAL")]
    Manual,
    #[serde(rename = "SCHEDULE")]
    Schedule,
    #[serde(rename = "WEBHOOK")]
    Webhook,
}

impl std::fmt::Display for AgenticWorkflowRunTrigger {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Manual => write!(f, "MANUAL"),
            Self::Schedule => write!(f, "SCHEDULE"),
            Self::Webhook => write!(f, "WEBHOOK"),
        }
    }
}

impl Default for AgenticWorkflowRunTrigger {
    fn default() -> AgenticWorkflowRunTrigger {
        Self::Manual
    }
}
