/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgenticWorkflowRequest {
    /// name is case insensitive
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// CIDR ranges the incoming webhook request's source IP is checked against
    #[serde(
        rename = "webhook_ip_allowlist",
        skip_serializing_if = "Option::is_none"
    )]
    pub webhook_ip_allowlist: Option<Vec<String>>,
    #[serde(rename = "docker_fragment", skip_serializing_if = "Option::is_none")]
    pub docker_fragment: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Raw JSON blob describing the MCP servers configured for this workflow
    #[serde(rename = "mcp", skip_serializing_if = "Option::is_none")]
    pub mcp: Option<String>,
    /// Organization MCP servers used by this workflow
    #[serde(rename = "mcp_server_ids", skip_serializing_if = "Option::is_none")]
    pub mcp_server_ids: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<models::AgenticWorkflowOutput>>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<models::AgenticWorkflowModelRequest>,
    #[serde(
        rename = "project_repositories",
        skip_serializing_if = "Option::is_none"
    )]
    pub project_repositories: Option<Vec<models::AgenticWorkflowProjectRepository>>,
    #[serde(rename = "agent_prompt", skip_serializing_if = "Option::is_none")]
    pub agent_prompt: Option<String>,
    #[serde(rename = "governance", skip_serializing_if = "Option::is_none")]
    pub governance: Option<models::AgenticWorkflowGovernance>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<models::AgenticWorkflowResources>,
    /// Cron schedule firing runs of this workflow, on top of the webhook every workflow already has. Omit it, or send null, for a webhook-only workflow.
    #[serde(
        rename = "schedule",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub schedule: Option<Option<models::AgenticWorkflowScheduleRequest>>,
}

impl AgenticWorkflowRequest {
    pub fn new(name: String) -> AgenticWorkflowRequest {
        AgenticWorkflowRequest {
            name,
            description: None,
            webhook_ip_allowlist: None,
            docker_fragment: None,
            enabled: None,
            mcp: None,
            mcp_server_ids: None,
            outputs: None,
            model: None,
            project_repositories: None,
            agent_prompt: None,
            governance: None,
            resources: None,
            schedule: None,
        }
    }
}
