/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgenticWorkflowRequest {
    /// name is case insensitive
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// CIDR ranges the incoming webhook request's source IP is checked against
    #[serde(
        rename = "webhook_ip_allowlist",
        skip_serializing_if = "Option::is_none"
    )]
    pub webhook_ip_allowlist: Option<Vec<String>>,
    #[serde(rename = "docker_fragment", skip_serializing_if = "Option::is_none")]
    pub docker_fragment: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Raw JSON blob describing the MCP servers configured for this workflow
    #[serde(rename = "mcp", skip_serializing_if = "Option::is_none")]
    pub mcp: Option<String>,
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<models::AgenticWorkflowOutput>>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<models::AgenticWorkflowModelRequest>,
    #[serde(
        rename = "project_repositories",
        skip_serializing_if = "Option::is_none"
    )]
    pub project_repositories: Option<Vec<models::AgenticWorkflowProjectRepository>>,
    #[serde(rename = "agent_prompt", skip_serializing_if = "Option::is_none")]
    pub agent_prompt: Option<String>,
    #[serde(rename = "governance", skip_serializing_if = "Option::is_none")]
    pub governance: Option<models::AgenticWorkflowGovernance>,
}

impl AgenticWorkflowRequest {
    pub fn new(name: String) -> AgenticWorkflowRequest {
        AgenticWorkflowRequest {
            name,
            description: None,
            webhook_ip_allowlist: None,
            docker_fragment: None,
            enabled: None,
            mcp: None,
            outputs: None,
            model: None,
            project_repositories: None,
            agent_prompt: None,
            governance: None,
        }
    }
}
