/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertRuleResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "source")]
    pub source: models::AlertRuleSource,
    /// Name of the alert rule
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "state")]
    pub state: models::AlertRuleState,
    /// Organization identifier
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    ///  Cluster identifier
    #[serde(rename = "cluster_id")]
    pub cluster_id: uuid::Uuid,
    /// Description of what the alert monitors
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "tag")]
    pub tag: String,
    #[serde(rename = "condition")]
    pub condition: models::AlertRuleCondition,
    /// Duration the condition must be true before firing (ISO-8601 duration format)
    #[serde(rename = "for_duration")]
    pub for_duration: String,
    #[serde(rename = "severity")]
    pub severity: models::AlertSeverity,
    /// Whether the alert rule is enabled
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// List of alert receiver IDs to send notifications to
    #[serde(rename = "alert_receiver_ids")]
    pub alert_receiver_ids: Vec<uuid::Uuid>,
    #[serde(rename = "presentation")]
    pub presentation: models::AlertPresentationResponse,
    #[serde(rename = "target")]
    pub target: models::AlertTarget,
    /// Indicates whether the current version of the alert has been synced with the alerting system. If false, an outdated version is currently deployed.
    #[serde(rename = "is_up_to_date")]
    pub is_up_to_date: bool,
    /// when the alert starts firing
    #[serde(rename = "starts_at", skip_serializing_if = "Option::is_none")]
    pub starts_at: Option<String>,
}

impl AlertRuleResponse {
    pub fn new(
        id: uuid::Uuid,
        created_at: String,
        source: models::AlertRuleSource,
        name: String,
        state: models::AlertRuleState,
        organization_id: uuid::Uuid,
        cluster_id: uuid::Uuid,
        description: String,
        tag: String,
        condition: models::AlertRuleCondition,
        for_duration: String,
        severity: models::AlertSeverity,
        enabled: bool,
        alert_receiver_ids: Vec<uuid::Uuid>,
        presentation: models::AlertPresentationResponse,
        target: models::AlertTarget,
        is_up_to_date: bool,
    ) -> AlertRuleResponse {
        AlertRuleResponse {
            id,
            created_at,
            updated_at: None,
            source,
            name,
            state,
            organization_id,
            cluster_id,
            description,
            tag,
            condition,
            for_duration,
            severity,
            enabled,
            alert_receiver_ids,
            presentation,
            target,
            is_up_to_date,
            starts_at: None,
        }
    }
}
