/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlertRuleResponseBase : Base schema for alert rule responses with discriminator
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "source")]
pub enum AlertRuleResponseBase {
    #[serde(rename = "GHOST")]
    GhostAlertRuleResponse {
        /// Name of the alert rule
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "state")]
        state: models::AlertRuleState,
    },
    #[serde(rename = "MANAGED")]
    AlertRuleResponse {
        /// Name of the alert rule
        #[serde(rename = "name")]
        name: String,
        #[serde(rename = "state")]
        state: models::AlertRuleState,
    },
}

impl Default for AlertRuleResponseBase {
    fn default() -> Self {
        Self::GhostAlertRuleResponse {
            name: Default::default(),
            state: Default::default(),
        }
    }
}
