/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiVariableTypeEnum : type of the environment variable (VALUE, FILE, ALIAS, OVERRIDE, BUIT_IN, EXTERNAL_SECRET)
/// type of the environment variable (VALUE, FILE, ALIAS, OVERRIDE, BUIT_IN, EXTERNAL_SECRET)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiVariableTypeEnum {
    #[serde(rename = "VALUE")]
    Value,
    #[serde(rename = "ALIAS")]
    Alias,
    #[serde(rename = "OVERRIDE")]
    Override,
    #[serde(rename = "BUILT_IN")]
    BuiltIn,
    #[serde(rename = "FILE")]
    File,
    #[serde(rename = "EXTERNAL_SECRET")]
    ExternalSecret,
}

impl std::fmt::Display for ApiVariableTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Value => write!(f, "VALUE"),
            Self::Alias => write!(f, "ALIAS"),
            Self::Override => write!(f, "OVERRIDE"),
            Self::BuiltIn => write!(f, "BUILT_IN"),
            Self::File => write!(f, "FILE"),
            Self::ExternalSecret => write!(f, "EXTERNAL_SECRET"),
        }
    }
}

impl Default for ApiVariableTypeEnum {
    fn default() -> ApiVariableTypeEnum {
        Self::Value
    }
}
