/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArgoCdCredentialsRequest {
    /// The URL of the ArgoCD instance (e.g. https://argocd.example.com)
    #[serde(rename = "argocd_url")]
    pub argocd_url: String,
    /// ArgoCD API authentication token
    #[serde(rename = "argocd_token")]
    pub argocd_token: String,
}

impl ArgoCdCredentialsRequest {
    pub fn new(argocd_url: String, argocd_token: String) -> ArgoCdCredentialsRequest {
        ArgoCdCredentialsRequest {
            argocd_url,
            argocd_token,
        }
    }
}
