/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachServiceToDeploymentStageRequest {
    /// When true, marks the service as skipped (excluded from environment-level bulk deployments) while keeping it in the specified stage. When false or omitted, the service is moved to the specified stage and un-skipped.
    #[serde(rename = "is_skipped", skip_serializing_if = "Option::is_none")]
    pub is_skipped: Option<bool>,
}

impl AttachServiceToDeploymentStageRequest {
    pub fn new() -> AttachServiceToDeploymentStageRequest {
        AttachServiceToDeploymentStageRequest { is_skipped: None }
    }
}
