/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutomaticallyConfiguredAuthDto {
    #[serde(rename = "mode")]
    pub mode: Mode,
}

impl AutomaticallyConfiguredAuthDto {
    pub fn new(mode: Mode) -> AutomaticallyConfiguredAuthDto {
        AutomaticallyConfiguredAuthDto { mode }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "AUTOMATICALLY_CONFIGURED")]
    AutomaticallyConfigured,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::AutomaticallyConfigured
    }
}
