/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvailableContainerRegistryResponse {
    #[serde(rename = "kind")]
    pub kind: models::ContainerRegistryKindEnum,
    #[serde(rename = "required_config")]
    pub required_config: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "is_mandatory")]
    pub is_mandatory: bool,
}

impl AvailableContainerRegistryResponse {
    pub fn new(kind: models::ContainerRegistryKindEnum, required_config: std::collections::HashMap<String, serde_json::Value>, is_mandatory: bool) -> AvailableContainerRegistryResponse {
        AvailableContainerRegistryResponse {
            kind,
            required_config,
            is_mandatory,
        }
    }
}

