/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AwsCredentialsRequest {
    AwsRoleCredentialsRequest(models::AwsRoleCredentialsRequest),
    AwsStaticCredentialsRequest(models::AwsStaticCredentialsRequest),
}

impl Default for AwsCredentialsRequest {
    fn default() -> Self {
        Self::AwsRoleCredentialsRequest(Default::default())
    }
}
