/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsSecretManagerEndpointDto {
    #[serde(rename = "mode")]
    pub mode: Mode,
    #[serde(rename = "region")]
    pub region: String,
}

impl AwsSecretManagerEndpointDto {
    pub fn new(mode: Mode, region: String) -> AwsSecretManagerEndpointDto {
        AwsSecretManagerEndpointDto { mode, region }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "AWS_SECRET_MANAGER")]
    AwsSecretManager,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::AwsSecretManager
    }
}
