/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueprintManifestResponse {
    /// Form fields the console renders for the user (variables + auto-sourced context variables).
    #[serde(rename = "results")]
    pub results: Vec<models::BlueprintManifestResponseResultsInner>,
    #[serde(rename = "engine", skip_serializing_if = "Option::is_none")]
    pub engine: Option<models::BlueprintManifestEngineSpec>,
}

impl BlueprintManifestResponse {
    pub fn new(
        results: Vec<models::BlueprintManifestResponseResultsInner>,
    ) -> BlueprintManifestResponse {
        BlueprintManifestResponse {
            results,
            engine: None,
        }
    }
}
