/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BlueprintManifestCredentialsConfig : Credentials override metadata. Catalog default + which values are allowed and whether the user can override at all.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueprintManifestCredentialsConfig {
    #[serde(
        rename = "default",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default: Option<Option<String>>,
    #[serde(
        rename = "allowed_values",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub allowed_values: Option<Option<Vec<String>>>,
    #[serde(rename = "overridable", skip_serializing_if = "Option::is_none")]
    pub overridable: Option<bool>,
}

impl BlueprintManifestCredentialsConfig {
    /// Credentials override metadata. Catalog default + which values are allowed and whether the user can override at all.
    pub fn new() -> BlueprintManifestCredentialsConfig {
        BlueprintManifestCredentialsConfig {
            default: None,
            allowed_values: None,
            overridable: None,
        }
    }
}
