/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueprintManifestEngineOpenTofu {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "provider")]
    pub provider: models::CloudVendorEnum,
    #[serde(rename = "opentofu")]
    pub opentofu: models::BlueprintManifestVersionBlock,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<models::BlueprintManifestCredentialsConfig>,
    #[serde(rename = "backend", skip_serializing_if = "Option::is_none")]
    pub backend: Option<models::BlueprintManifestBackendConfig>,
    #[serde(
        rename = "timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timeout: Option<Option<i64>>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<models::BlueprintManifestResourcesConfig>,
}

impl BlueprintManifestEngineOpenTofu {
    pub fn new(
        r#type: Type,
        provider: models::CloudVendorEnum,
        opentofu: models::BlueprintManifestVersionBlock,
    ) -> BlueprintManifestEngineOpenTofu {
        BlueprintManifestEngineOpenTofu {
            r#type,
            provider,
            opentofu,
            credentials: None,
            backend: None,
            timeout: None,
            resources: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "opentofu")]
    Opentofu,
}

impl Default for Type {
    fn default() -> Type {
        Self::Opentofu
    }
}
