/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueprintUpdateNewOptionalValue {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "default_value",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_value: Option<Option<String>>,
}

impl BlueprintUpdateNewOptionalValue {
    pub fn new(name: String) -> BlueprintUpdateNewOptionalValue {
        BlueprintUpdateNewOptionalValue {
            name,
            default_value: None,
        }
    }
}
