/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueprintCreateRequest {
    /// Display name for the service
    #[serde(rename = "name")]
    pub name: String,
    /// Catalog tag identifying the blueprint version
    #[serde(rename = "tag")]
    pub tag: String,
    /// Icon URL for the service
    #[serde(rename = "icon")]
    pub icon: String,
    /// Variable overrides for the blueprint
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<Vec<models::BlueprintVariableRequest>>,
    /// Partial spec overrides merged on top of the blueprint manifest
    #[serde(
        rename = "specOverrides",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub spec_overrides: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl BlueprintCreateRequest {
    pub fn new(name: String, tag: String, icon: String) -> BlueprintCreateRequest {
        BlueprintCreateRequest {
            name,
            tag,
            icon,
            variables: None,
            spec_overrides: None,
        }
    }
}
