/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueprintManifestEngineHelm {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "chart")]
    pub chart: models::BlueprintManifestChartConfig,
    #[serde(
        rename = "timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timeout: Option<Option<i64>>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<models::BlueprintManifestResourcesConfig>,
}

impl BlueprintManifestEngineHelm {
    pub fn new(
        r#type: Type,
        chart: models::BlueprintManifestChartConfig,
    ) -> BlueprintManifestEngineHelm {
        BlueprintManifestEngineHelm {
            r#type,
            chart,
            timeout: None,
            resources: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "helm")]
    Helm,
}

impl Default for Type {
    fn default() -> Type {
        Self::Helm
    }
}
