/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueprintUpdateNewRequiredValue {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: models::BlueprintManifestFieldType,
    /// Values the user may choose from. Null = unrestricted.
    #[serde(
        rename = "allowed_values",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub allowed_values: Option<Option<Vec<String>>>,
    #[serde(rename = "is_secret")]
    pub is_secret: bool,
}

impl BlueprintUpdateNewRequiredValue {
    pub fn new(
        name: String,
        r#type: models::BlueprintManifestFieldType,
        is_secret: bool,
    ) -> BlueprintUpdateNewRequiredValue {
        BlueprintUpdateNewRequiredValue {
            name,
            r#type,
            allowed_values: None,
            is_secret,
        }
    }
}
