/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlueprintManifestUserProvidedBackend {
    /// Terraform backend type (e.g. \"s3\", \"gcs\", \"azurerm\").
    #[serde(rename = "type")]
    pub r#type: String,
    /// Static backend config (bucket, region, etc.).
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<std::collections::HashMap<String, String>>,
}

impl BlueprintManifestUserProvidedBackend {
    pub fn new(r#type: String) -> BlueprintManifestUserProvidedBackend {
        BlueprintManifestUserProvidedBackend {
            r#type,
            config: None,
        }
    }
}
