/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildSettings : Build configuration settings for the service. When sent, it replaces all six values entirely — omitted properties fall back to their defaults, not to the service's current values.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildSettings {
    /// Maximum build timeout in seconds
    #[serde(rename = "timeout_max_sec", skip_serializing_if = "Option::is_none")]
    pub timeout_max_sec: Option<i32>,
    /// Maximum CPU resources for the build (in millicores)
    #[serde(rename = "cpu_max_in_milli", skip_serializing_if = "Option::is_none")]
    pub cpu_max_in_milli: Option<i32>,
    /// Maximum RAM resources for the build (in GiB)
    #[serde(rename = "ram_max_in_gib", skip_serializing_if = "Option::is_none")]
    pub ram_max_in_gib: Option<i32>,
    /// Ephemeral storage for the build (in GiB). When null, the platform default is used.
    #[serde(
        rename = "ephemeral_storage_in_gib",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ephemeral_storage_in_gib: Option<Option<i32>>,
    /// Disable buildkit registry cache during build
    #[serde(
        rename = "disable_buildkit_cache",
        skip_serializing_if = "Option::is_none"
    )]
    pub disable_buildkit_cache: Option<bool>,
    /// Skip git submodules update when cloning the repository
    #[serde(
        rename = "skip_git_submodules",
        skip_serializing_if = "Option::is_none"
    )]
    pub skip_git_submodules: Option<bool>,
}

impl BuildSettings {
    /// Build configuration settings for the service. When sent, it replaces all six values entirely — omitted properties fall back to their defaults, not to the service's current values.
    pub fn new() -> BuildSettings {
        BuildSettings {
            timeout_max_sec: None,
            cpu_max_in_milli: None,
            ram_max_in_gib: None,
            ephemeral_storage_in_gib: None,
            disable_buildkit_cache: None,
            skip_git_submodules: None,
        }
    }
}
