/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelAgenticWorkflowDeploymentRequest {
    /// When false, the engine stops the deployment at the next safe point, letting the workflow's job terminate on its own. When true it stops waiting for that job and abandons it immediately.
    #[serde(rename = "force_cancel", skip_serializing_if = "Option::is_none")]
    pub force_cancel: Option<bool>,
}

impl CancelAgenticWorkflowDeploymentRequest {
    pub fn new() -> CancelAgenticWorkflowDeploymentRequest {
        CancelAgenticWorkflowDeploymentRequest { force_cancel: None }
    }
}
