/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudflareDnsProviderRequest {
    #[serde(rename = "provider")]
    pub provider: Provider,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "email")]
    pub email: String,
    /// Cloudflare API token. Must be provided when editing Cloudflare DNS provider.
    #[serde(rename = "api_token")]
    pub api_token: String,
    #[serde(rename = "proxied", skip_serializing_if = "Option::is_none")]
    pub proxied: Option<bool>,
}

impl CloudflareDnsProviderRequest {
    pub fn new(
        provider: Provider,
        domain: String,
        email: String,
        api_token: String,
    ) -> CloudflareDnsProviderRequest {
        CloudflareDnsProviderRequest {
            provider,
            domain,
            email,
            api_token,
            proxied: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "CLOUDFLARE")]
    Cloudflare,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Cloudflare
    }
}
