/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterAnalysisResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "cluster_id")]
    pub cluster_id: uuid::Uuid,
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    #[serde(rename = "kind")]
    pub kind: models::ClusterAnalysisKind,
    #[serde(rename = "status")]
    pub status: models::ClusterAnalysisStatus,
    #[serde(rename = "output_format")]
    pub output_format: models::ClusterAnalysisOutputFormat,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "triggered_by")]
    pub triggered_by: String,
    #[serde(
        rename = "error_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error_message: Option<Option<String>>,
}

impl ClusterAnalysisResponse {
    pub fn new(
        id: uuid::Uuid,
        cluster_id: uuid::Uuid,
        organization_id: uuid::Uuid,
        kind: models::ClusterAnalysisKind,
        status: models::ClusterAnalysisStatus,
        output_format: models::ClusterAnalysisOutputFormat,
        created_at: String,
        updated_at: String,
        triggered_by: String,
    ) -> ClusterAnalysisResponse {
        ClusterAnalysisResponse {
            id,
            cluster_id,
            organization_id,
            kind,
            status,
            output_format,
            created_at,
            updated_at,
            triggered_by,
            error_message: None,
        }
    }
}
