/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterOverviewResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "cloud_provider")]
    pub cloud_provider: models::CloudVendorEnum,
    #[serde(rename = "is_demo")]
    pub is_demo: bool,
}

impl ClusterOverviewResponse {
    pub fn new(
        id: uuid::Uuid,
        name: String,
        cloud_provider: models::CloudVendorEnum,
        is_demo: bool,
    ) -> ClusterOverviewResponse {
        ClusterOverviewResponse {
            id,
            name,
            cloud_provider,
            is_demo,
        }
    }
}
