/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterStatus {
    #[serde(rename = "cluster_id")]
    pub cluster_id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: models::ClusterStateEnum,
    #[serde(rename = "is_deployed")]
    pub is_deployed: bool,
    #[serde(
        rename = "next_k8s_available_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_k8s_available_version: Option<Option<String>>,
    #[serde(
        rename = "last_execution_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_execution_id: Option<Option<String>>,
    #[serde(
        rename = "cluster_lock",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cluster_lock: Option<Option<models::ClusterLock>>,
    #[serde(
        rename = "last_deployment_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_deployment_date: Option<Option<String>>,
    #[serde(rename = "reason")]
    pub reason: models::DeploymentInfraReason,
}

impl ClusterStatus {
    pub fn new(
        cluster_id: uuid::Uuid,
        status: models::ClusterStateEnum,
        is_deployed: bool,
        reason: models::DeploymentInfraReason,
    ) -> ClusterStatus {
        ClusterStatus {
            cluster_id,
            status,
            is_deployed,
            next_k8s_available_version: None,
            last_execution_id: None,
            cluster_lock: None,
            last_deployment_date: None,
            reason,
        }
    }
}
