/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterFeatureGcpExistingVpc {
    #[serde(rename = "vpc_name")]
    pub vpc_name: String,
    #[serde(rename = "vpc_project_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vpc_project_id: Option<Option<String>>,
    #[serde(rename = "subnetwork_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subnetwork_name: Option<Option<String>>,
    #[serde(rename = "ip_range_services_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ip_range_services_name: Option<Option<String>>,
    #[serde(rename = "ip_range_pods_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ip_range_pods_name: Option<Option<String>>,
    #[serde(rename = "additional_ip_range_pods_names", skip_serializing_if = "Option::is_none")]
    pub additional_ip_range_pods_names: Option<Vec<String>>,
}

impl ClusterFeatureGcpExistingVpc {
    pub fn new(vpc_name: String) -> ClusterFeatureGcpExistingVpc {
        ClusterFeatureGcpExistingVpc {
            vpc_name,
            vpc_project_id: None,
            subnetwork_name: None,
            ip_range_services_name: None,
            ip_range_pods_name: None,
            additional_ip_range_pods_names: None,
        }
    }
}

