/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterInfrastructureEksAnywhereParameters {
    #[serde(rename = "git_repository")]
    pub git_repository: models::ClusterEksAnywhereGitRepository,
    /// Path to the EKS Anywhere cluster YAML file in the git repository
    #[serde(rename = "yaml_file_path")]
    pub yaml_file_path: String,
    #[serde(rename = "cluster_backup", skip_serializing_if = "Option::is_none")]
    pub cluster_backup: Option<models::ClusterInfrastructureEksAnywhereBackupParameters>,
}

impl ClusterInfrastructureEksAnywhereParameters {
    pub fn new(
        git_repository: models::ClusterEksAnywhereGitRepository,
        yaml_file_path: String,
    ) -> ClusterInfrastructureEksAnywhereParameters {
        ClusterInfrastructureEksAnywhereParameters {
            git_repository,
            yaml_file_path,
            cluster_backup: None,
        }
    }
}
