/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterOperatorFleetInventoryResponse {
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    #[serde(rename = "cluster_id")]
    pub cluster_id: uuid::Uuid,
    #[serde(rename = "cluster_name")]
    pub cluster_name: String,
    #[serde(rename = "cluster_kind")]
    pub cluster_kind: models::SelfManagedClusterKind,
    /// Whether the cluster is explicitly routed through the Operator execution path.
    #[serde(rename = "attached")]
    pub attached: bool,
    /// Whether the last heartbeat is within the Operator presence window.
    #[serde(rename = "connected")]
    pub connected: bool,
    #[serde(
        rename = "last_heartbeat",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_heartbeat: Option<Option<String>>,
    #[serde(
        rename = "desired_image_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub desired_image_version: Option<Option<String>>,
    #[serde(
        rename = "reported_image_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reported_image_version: Option<Option<String>>,
    #[serde(
        rename = "desired_chart_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub desired_chart_version: Option<Option<String>>,
    #[serde(
        rename = "reported_chart_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reported_chart_version: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: models::ClusterOperatorFleetStatus,
}

impl ClusterOperatorFleetInventoryResponse {
    pub fn new(
        organization_id: uuid::Uuid,
        cluster_id: uuid::Uuid,
        cluster_name: String,
        cluster_kind: models::SelfManagedClusterKind,
        attached: bool,
        connected: bool,
        status: models::ClusterOperatorFleetStatus,
    ) -> ClusterOperatorFleetInventoryResponse {
        ClusterOperatorFleetInventoryResponse {
            organization_id,
            cluster_id,
            cluster_name,
            cluster_kind,
            attached,
            connected,
            last_heartbeat: None,
            desired_image_version: None,
            reported_image_version: None,
            desired_chart_version: None,
            reported_chart_version: None,
            status,
        }
    }
}
