/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterInfrastructureCertManagerChartParameters {
    #[serde(
        rename = "kubernetes_namespace",
        skip_serializing_if = "Option::is_none"
    )]
    pub kubernetes_namespace: Option<String>,
}

impl ClusterInfrastructureCertManagerChartParameters {
    pub fn new() -> ClusterInfrastructureCertManagerChartParameters {
        ClusterInfrastructureCertManagerChartParameters {
            kubernetes_namespace: None,
        }
    }
}
