/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterOperatorStatusResponse {
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    #[serde(rename = "cluster_id")]
    pub cluster_id: uuid::Uuid,
    /// Whether the last heartbeat is within the Operator presence window.
    #[serde(rename = "operator_connected")]
    pub operator_connected: bool,
    #[serde(
        rename = "last_heartbeat",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_heartbeat: Option<Option<String>>,
    /// Display version reported by the Operator. For the POC version-reporting heartbeat, the official chart sets this to the exact installed image tag. Legacy Operators can report opaque build metadata instead.
    #[serde(
        rename = "operator_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub operator_version: Option<Option<String>>,
    #[serde(
        rename = "controller_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub controller_version: Option<Option<String>>,
    #[serde(
        rename = "request_schema_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub request_schema_version: Option<Option<String>>,
    /// Image tag currently selected for a newly compiled Operator bootstrap.
    #[serde(
        rename = "desired_image_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub desired_image_version: Option<Option<String>>,
    /// Helm chart version currently selected for a newly compiled Operator bootstrap.
    #[serde(
        rename = "desired_chart_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub desired_chart_version: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: models::ClusterOperatorFleetStatus,
    /// Helm chart version reported by the Operator, even without immutable identity.
    #[serde(
        rename = "reported_chart_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reported_chart_version: Option<Option<String>>,
    #[serde(
        rename = "reported_identity",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reported_identity: Option<Option<models::ReportedClusterOperatorIdentity>>,
}

impl ClusterOperatorStatusResponse {
    pub fn new(
        organization_id: uuid::Uuid,
        cluster_id: uuid::Uuid,
        operator_connected: bool,
        status: models::ClusterOperatorFleetStatus,
    ) -> ClusterOperatorStatusResponse {
        ClusterOperatorStatusResponse {
            organization_id,
            cluster_id,
            operator_connected,
            last_heartbeat: None,
            operator_version: None,
            controller_version: None,
            request_schema_version: None,
            desired_image_version: None,
            desired_chart_version: None,
            status,
            reported_chart_version: None,
            reported_identity: None,
        }
    }
}
