/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterPlatformConfigurationRequest : Complete platform configuration of a cluster. It replaces the stored one; omitted layerSelections and managedConfig are stored empty.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterPlatformConfigurationRequest {
    #[serde(rename = "platform")]
    pub platform: models::PlatformSelection,
    /// String values keyed first by component key and then by input key
    #[serde(rename = "clusterInputs")]
    pub cluster_inputs:
        std::collections::HashMap<String, std::collections::HashMap<String, String>>,
}

impl ClusterPlatformConfigurationRequest {
    /// Complete platform configuration of a cluster. It replaces the stored one; omitted layerSelections and managedConfig are stored empty.
    pub fn new(
        platform: models::PlatformSelection,
        cluster_inputs: std::collections::HashMap<
            String,
            std::collections::HashMap<String, String>,
        >,
    ) -> ClusterPlatformConfigurationRequest {
        ClusterPlatformConfigurationRequest {
            platform,
            cluster_inputs,
        }
    }
}
