/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerNetwork {
    /// Specify if the sticky session option (also called persistant session) is activated or not for this container. If activated, user will be redirected by the load balancer to the same instance each time he access to the container.
    #[serde(rename = "sticky_session", skip_serializing_if = "Option::is_none")]
    pub sticky_session: Option<bool>,
}

impl ContainerNetwork {
    pub fn new() -> ContainerNetwork {
        ContainerNetwork {
            sticky_session: None,
        }
    }
}
