/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnterpriseConnectionAccess {
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "enforce_group_sync")]
    pub enforce_group_sync: bool,
}

impl EnterpriseConnectionAccess {
    pub fn new(
        organization_id: uuid::Uuid,
        role: String,
        enforce_group_sync: bool,
    ) -> EnterpriseConnectionAccess {
        EnterpriseConnectionAccess {
            organization_id,
            role,
            enforce_group_sync,
        }
    }
}
