/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvironmentVariableRequest {
    /// key is case sensitive.
    #[serde(rename = "key")]
    pub key: String,
    /// value of the env variable.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// should be set for file only. variable mount path makes variable a file (where file should be mounted).
    #[serde(rename = "mount_path", skip_serializing_if = "Option::is_none")]
    pub mount_path: Option<String>,
    /// optional variable description (255 characters maximum)
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "enable_interpolation_in_file",
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_interpolation_in_file: Option<bool>,
}

impl EnvironmentVariableRequest {
    pub fn new(key: String) -> EnvironmentVariableRequest {
        EnvironmentVariableRequest {
            key,
            value: None,
            mount_path: None,
            description: None,
            enable_interpolation_in_file: None,
        }
    }
}
