/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HelmRequestAllOfValuesOverrideFileRawValues {
    /// The name of the value file
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The content of the value file
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl HelmRequestAllOfValuesOverrideFileRawValues {
    pub fn new() -> HelmRequestAllOfValuesOverrideFileRawValues {
        HelmRequestAllOfValuesOverrideFileRawValues {
            name: None,
            content: None,
        }
    }
}
