/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobForceEvent {
    #[serde(rename = "START")]
    Start,
    #[serde(rename = "STOP")]
    Stop,
    #[serde(rename = "DELETE")]
    Delete,
    #[serde(rename = "CRON")]
    Cron,
}

impl std::fmt::Display for JobForceEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Start => write!(f, "START"),
            Self::Stop => write!(f, "STOP"),
            Self::Delete => write!(f, "DELETE"),
            Self::Cron => write!(f, "CRON"),
        }
    }
}

impl Default for JobForceEvent {
    fn default() -> JobForceEvent {
        Self::Start
    }
}
