/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KarpenterStableNodePoolOverride : The optional `drift_blocking` setting defines one recurring UTC window during which Karpenter drift disruptions are blocked on the stable node pool. When omitted on creation or disabled, drift behavior is unchanged; omitting it on update preserves the existing setting. When enabled, `days` must contain all seven weekdays and `duration` must be between PT1M and PT23H, leaving at least one hour each day when drift is permitted.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KarpenterStableNodePoolOverride {
    #[serde(rename = "consolidation", skip_serializing_if = "Option::is_none")]
    pub consolidation: Option<models::KarpenterNodePoolConsolidation>,
    #[serde(rename = "drift_blocking", skip_serializing_if = "Option::is_none")]
    pub drift_blocking: Option<models::KarpenterNodePoolConsolidation>,
    #[serde(rename = "limits", skip_serializing_if = "Option::is_none")]
    pub limits: Option<models::KarpenterNodePoolLimits>,
    /// Whether this node pool runs on spot instances. `null` or absent means the pool inherits the deprecated top-level `spot_enabled`: on write that value applies to this pool, on read only a deviating value is surfaced.
    #[serde(
        rename = "spot_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub spot_enabled: Option<Option<bool>>,
    /// Time to wait before consolidating empty or underutilized nodes (e.g., 1m, 10m, 1h). Maximum: 24h
    #[serde(rename = "consolidate_after", skip_serializing_if = "Option::is_none")]
    pub consolidate_after: Option<String>,
}

impl KarpenterStableNodePoolOverride {
    /// The optional `drift_blocking` setting defines one recurring UTC window during which Karpenter drift disruptions are blocked on the stable node pool. When omitted on creation or disabled, drift behavior is unchanged; omitting it on update preserves the existing setting. When enabled, `days` must contain all seven weekdays and `duration` must be between PT1M and PT23H, leaving at least one hour each day when drift is permitted.
    pub fn new() -> KarpenterStableNodePoolOverride {
        KarpenterStableNodePoolOverride {
            consolidation: None,
            drift_blocking: None,
            limits: None,
            spot_enabled: None,
            consolidate_after: None,
        }
    }
}
