/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KubernetesServiceSpec {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "ports", skip_serializing_if = "Option::is_none")]
    pub ports: Option<Vec<models::KubernetesServicePort>>,
    #[serde(rename = "selectors", skip_serializing_if = "Option::is_none")]
    pub selectors: Option<Vec<models::KubernetesSelector>>,
}

impl KubernetesServiceSpec {
    pub fn new() -> KubernetesServiceSpec {
        KubernetesServiceSpec {
            r#type: None,
            ports: None,
            selectors: None,
        }
    }
}
