/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LifecycleTemplateResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    /// location of the template
    #[serde(rename = "sourceUrl")]
    pub source_url: String,
    #[serde(rename = "cloud_provider")]
    pub cloud_provider: models::CloudProviderEnum,
    /// lis of pre-defined command for each event
    #[serde(rename = "events")]
    pub events: Vec<models::LifecycleTemplateResponseEventsInner>,
    /// Job max allowed duration in seconds. After this allowed time, the job is going to be killed.
    #[serde(rename = "max_duration_in_sec")]
    pub max_duration_in_sec: i32,
    #[serde(rename = "resources")]
    pub resources: models::LifecycleTemplateResponseResources,
    /// Variables to inject at the creation of this lifecycle job
    #[serde(rename = "variables")]
    pub variables: Vec<models::LifecycleTemplateResponseVariablesInner>,
    /// Dockerfile of the template
    #[serde(rename = "dockerfile")]
    pub dockerfile: String,
}

impl LifecycleTemplateResponse {
    pub fn new(
        id: uuid::Uuid,
        name: String,
        description: String,
        source_url: String,
        cloud_provider: models::CloudProviderEnum,
        events: Vec<models::LifecycleTemplateResponseEventsInner>,
        max_duration_in_sec: i32,
        resources: models::LifecycleTemplateResponseResources,
        variables: Vec<models::LifecycleTemplateResponseVariablesInner>,
        dockerfile: String,
    ) -> LifecycleTemplateResponse {
        LifecycleTemplateResponse {
            id,
            name,
            description,
            source_url,
            cloud_provider,
            events,
            max_duration_in_sec,
            resources,
            variables,
            dockerfile,
        }
    }
}
