/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpServerRequest {
    /// Unique MCP server name within the organization
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// HTTPS URL of the remote MCP server
    #[serde(rename = "url")]
    pub url: String,
    /// HTTP headers sent to the MCP server. Header values are encrypted and never returned by the API.
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
}

impl McpServerRequest {
    pub fn new(name: String, url: String) -> McpServerRequest {
        McpServerRequest {
            name,
            description: None,
            url,
            headers: None,
        }
    }
}
