/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationCustomRoleUpdateRequestProjectPermissionsInner {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<uuid::Uuid>,
    /// If `is_admin` is `true`, the user is: - automatically `MANAGER` for each environment type - allowed to manage project deployment rules - able to delete the project    Note that `permissions` can then be ignored for this project
    #[serde(rename = "is_admin", skip_serializing_if = "Option::is_none")]
    pub is_admin: Option<bool>,
    /// Mandatory if `is_admin` is `false`   Should contain an entry for every environment type: - `DEVELOPMENT` - `PREVIEW` - `STAGING` - `PRODUCTION`
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<
        Vec<models::OrganizationCustomRoleUpdateRequestProjectPermissionsInnerPermissionsInner>,
    >,
}

impl OrganizationCustomRoleUpdateRequestProjectPermissionsInner {
    pub fn new() -> OrganizationCustomRoleUpdateRequestProjectPermissionsInner {
        OrganizationCustomRoleUpdateRequestProjectPermissionsInner {
            project_id: None,
            is_admin: None,
            permissions: None,
        }
    }
}
