/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationBillingUsageReportResponse {
    /// The URL of the report
    #[serde(rename = "report_url", skip_serializing_if = "Option::is_none")]
    pub report_url: Option<String>,
    /// The URL to delete the report. Use this URL to pro-actively delete the report before it expires
    #[serde(rename = "delete_report_url", skip_serializing_if = "Option::is_none")]
    pub delete_report_url: Option<String>,
}

impl OrganizationBillingUsageReportResponse {
    pub fn new() -> OrganizationBillingUsageReportResponse {
        OrganizationBillingUsageReportResponse {
            report_url: None,
            delete_report_url: None,
        }
    }
}
