/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationAgentApiToken {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// the Open Policy Agent (rego) policy evaluated on every request made with this token
    #[serde(rename = "opa_policy", skip_serializing_if = "Option::is_none")]
    pub opa_policy: Option<String>,
    #[serde(
        rename = "creator_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub creator_name: Option<Option<String>>,
    #[serde(
        rename = "expires_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<String>>,
}

impl OrganizationAgentApiToken {
    pub fn new(id: uuid::Uuid, created_at: String) -> OrganizationAgentApiToken {
        OrganizationAgentApiToken {
            id,
            created_at,
            updated_at: None,
            name: None,
            description: None,
            opa_policy: None,
            creator_name: None,
            expires_at: None,
        }
    }
}
