/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegistryMirroringModeEnum : Mirroring mode when deploying a service from a container registry - Cluster: This is not available on Scaleway. Images within the mirroring registry are organized by \"Qovery cluster\", meaning that the application deployed on the same cluster are all mirrored on the same repository. - Service: Images within the mirroring registry are organized by \"Qovery service\", each service has its own repository - Disabled: Only available on Scaleway Kapsule. Images are not copied into the cluster registry: pods pull them directly from the service container registry, with its credentials. Registries with temporary credentials (AWS ECR, Azure, GCP Artifact Registry) are still mirrored. Images built by Qovery still go to the cluster registry.
/// Mirroring mode when deploying a service from a container registry - Cluster: This is not available on Scaleway. Images within the mirroring registry are organized by \"Qovery cluster\", meaning that the application deployed on the same cluster are all mirrored on the same repository. - Service: Images within the mirroring registry are organized by \"Qovery service\", each service has its own repository - Disabled: Only available on Scaleway Kapsule. Images are not copied into the cluster registry: pods pull them directly from the service container registry, with its credentials. Registries with temporary credentials (AWS ECR, Azure, GCP Artifact Registry) are still mirrored. Images built by Qovery still go to the cluster registry.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RegistryMirroringModeEnum {
    #[serde(rename = "Cluster")]
    Cluster,
    #[serde(rename = "Service")]
    Service,
    #[serde(rename = "Disabled")]
    Disabled,
}

impl std::fmt::Display for RegistryMirroringModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Cluster => write!(f, "Cluster"),
            Self::Service => write!(f, "Service"),
            Self::Disabled => write!(f, "Disabled"),
        }
    }
}

impl Default for RegistryMirroringModeEnum {
    fn default() -> RegistryMirroringModeEnum {
        Self::Cluster
    }
}
