/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Route53DnsProviderRequest {
    #[serde(rename = "provider")]
    pub provider: Provider,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "credentials")]
    pub credentials: models::Route53StaticCredentialsRequest,
    #[serde(rename = "aws_region")]
    pub aws_region: String,
    #[serde(
        rename = "hosted_zone_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub hosted_zone_id: Option<Option<String>>,
}

impl Route53DnsProviderRequest {
    pub fn new(
        provider: Provider,
        domain: String,
        credentials: models::Route53StaticCredentialsRequest,
        aws_region: String,
    ) -> Route53DnsProviderRequest {
        Route53DnsProviderRequest {
            provider,
            domain,
            credentials,
            aws_region,
            hosted_zone_id: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "ROUTE53")]
    Route53,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Route53
    }
}
