/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Secret {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// key is case sensitive
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "overridden_secret", skip_serializing_if = "Option::is_none")]
    pub overridden_secret: Option<Box<models::SecretOverride>>,
    #[serde(rename = "aliased_secret", skip_serializing_if = "Option::is_none")]
    pub aliased_secret: Option<Box<models::SecretAlias>>,
    #[serde(rename = "scope")]
    pub scope: models::ApiVariableScopeEnum,
    #[serde(rename = "variable_type", skip_serializing_if = "Option::is_none")]
    pub variable_type: Option<models::ApiVariableTypeEnum>,
    #[serde(rename = "service_id", skip_serializing_if = "Option::is_none")]
    pub service_id: Option<uuid::Uuid>,
    #[serde(rename = "service_name", skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
    #[serde(rename = "service_type", skip_serializing_if = "Option::is_none")]
    pub service_type: Option<models::LinkedServiceTypeEnum>,
    /// Entity that created/own the variable (i.e: Qovery, Doppler)
    #[serde(rename = "owned_by", skip_serializing_if = "Option::is_none")]
    pub owned_by: Option<String>,
    /// optional variable description (255 characters maximum)
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "enable_interpolation_in_file", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enable_interpolation_in_file: Option<Option<bool>>,
}

impl Secret {
    pub fn new(id: uuid::Uuid, created_at: String, key: String, scope: models::ApiVariableScopeEnum) -> Secret {
        Secret {
            id,
            created_at,
            updated_at: None,
            key,
            overridden_secret: None,
            aliased_secret: None,
            scope,
            variable_type: None,
            service_id: None,
            service_name: None,
            service_type: None,
            owned_by: None,
            description: None,
            enable_interpolation_in_file: None,
        }
    }
}

