/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "mode")]
pub enum SecretManagerAuthenticationDto {
    #[serde(rename = "AUTOMATICALLY_CONFIGURED")]
    AutomaticallyConfigured(models::AutomaticallyConfiguredAuthDto),
    #[serde(rename = "AWS_ROLE_ARN")]
    AwsRoleArn(models::AwsRoleArnAuthDto),
    #[serde(rename = "AWS_STATIC_CREDENTIALS")]
    AwsStaticCredentials(models::AwsStaticCredentialsAuthDto),
    #[serde(rename = "GCP_JSON_CREDENTIALS")]
    GcpJsonCredentials(models::GcpJsonCredentialsAuthDto),
}

impl Default for SecretManagerAuthenticationDto {
    fn default() -> Self {
        Self::AutomaticallyConfigured(Default::default())
    }
}
