/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SelfManagedClusterPlatformSelection : Platform template release and configuration of a new self-managed cluster. Set templateKey and templateVersion together to select a release, or omit both and Qovery selects its self-managed platform template release; only one of them answers 400. layerSelections and managedConfig are validated against the selected release, and `{}` gives that release with its default configuration. Send them without templateKey and templateVersion only if you already know the components of the self-managed platform template; a client that renders the fields of a release must send that release's coordinates, and selections of mandatory layers are rejected. The response returns the selected release, and the cluster keeps it even if Qovery later selects another one.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelfManagedClusterPlatformSelection {
    /// Key of the platform template release, set together with templateVersion.
    #[serde(rename = "templateKey", skip_serializing_if = "Option::is_none")]
    pub template_key: Option<String>,
    /// Version of the platform template release, set together with templateKey.
    #[serde(rename = "templateVersion", skip_serializing_if = "Option::is_none")]
    pub template_version: Option<String>,
    #[serde(rename = "layerSelections", skip_serializing_if = "Option::is_none")]
    pub layer_selections: Option<std::collections::HashMap<String, bool>>,
    /// Component configuration values keyed by component key
    #[serde(rename = "managedConfig", skip_serializing_if = "Option::is_none")]
    pub managed_config: Option<
        std::collections::HashMap<String, std::collections::HashMap<String, serde_json::Value>>,
    >,
}

impl SelfManagedClusterPlatformSelection {
    /// Platform template release and configuration of a new self-managed cluster. Set templateKey and templateVersion together to select a release, or omit both and Qovery selects its self-managed platform template release; only one of them answers 400. layerSelections and managedConfig are validated against the selected release, and `{}` gives that release with its default configuration. Send them without templateKey and templateVersion only if you already know the components of the self-managed platform template; a client that renders the fields of a release must send that release's coordinates, and selections of mandatory layers are rejected. The response returns the selected release, and the cluster keeps it even if Qovery later selects another one.
    pub fn new() -> SelfManagedClusterPlatformSelection {
        SelfManagedClusterPlatformSelection {
            template_key: None,
            template_version: None,
            layer_selections: None,
            managed_config: None,
        }
    }
}
