/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SelfManagedClusterKind {
    #[serde(rename = "EKS_SELF_MANAGED")]
    EksSelfManaged,
    #[serde(rename = "SCW_SELF_MANAGED")]
    ScwSelfManaged,
    #[serde(rename = "GKE_SELF_MANAGED")]
    GkeSelfManaged,
    #[serde(rename = "AKS_SELF_MANAGED")]
    AksSelfManaged,
    #[serde(rename = "SELF_MANAGED")]
    SelfManaged,
}

impl std::fmt::Display for SelfManagedClusterKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::EksSelfManaged => write!(f, "EKS_SELF_MANAGED"),
            Self::ScwSelfManaged => write!(f, "SCW_SELF_MANAGED"),
            Self::GkeSelfManaged => write!(f, "GKE_SELF_MANAGED"),
            Self::AksSelfManaged => write!(f, "AKS_SELF_MANAGED"),
            Self::SelfManaged => write!(f, "SELF_MANAGED"),
        }
    }
}

impl Default for SelfManagedClusterKind {
    fn default() -> SelfManagedClusterKind {
        Self::EksSelfManaged
    }
}
