/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceActionEnum {
    #[serde(rename = "DEPLOY")]
    Deploy,
    #[serde(rename = "DELETE")]
    Delete,
    #[serde(rename = "RESTART")]
    Restart,
    #[serde(rename = "STOP")]
    Stop,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl std::fmt::Display for ServiceActionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Deploy => write!(f, "DEPLOY"),
            Self::Delete => write!(f, "DELETE"),
            Self::Restart => write!(f, "RESTART"),
            Self::Stop => write!(f, "STOP"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for ServiceActionEnum {
    fn default() -> ServiceActionEnum {
        Self::Deploy
    }
}
