/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StageStepMetric {
    #[serde(rename = "step_name", skip_serializing_if = "Option::is_none")]
    pub step_name: Option<models::StageStepMetricNameEnum>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::StepMetricStatusEnum>,
    /// The duration of the step in seconds.
    #[serde(rename = "duration_sec", skip_serializing_if = "Option::is_none")]
    pub duration_sec: Option<i32>,
}

impl StageStepMetric {
    pub fn new() -> StageStepMetric {
        StageStepMetric {
            step_name: None,
            status: None,
            duration_sec: None,
        }
    }
}
