/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TerraformDeployRequest {
    /// Commit to deploy for chart source.
    #[serde(rename = "git_commit_id", skip_serializing_if = "Option::is_none")]
    pub git_commit_id: Option<String>,
    #[serde(rename = "dry_run", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
}

impl TerraformDeployRequest {
    pub fn new() -> TerraformDeployRequest {
        TerraformDeployRequest {
            git_commit_id: None,
            dry_run: None,
        }
    }
}
