/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TerraformVariableDefinition : Represents a Terraform variable definition extracted from a Terraform file.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TerraformVariableDefinition {
    /// The name of the variable
    #[serde(rename = "key")]
    pub key: String,
    /// Whether the variable is marked as sensitive
    #[serde(rename = "sensitive")]
    pub sensitive: bool,
    /// The default value of the variable, or null if no default is provided
    #[serde(
        rename = "default",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default: Option<Option<String>>,
}

impl TerraformVariableDefinition {
    /// Represents a Terraform variable definition extracted from a Terraform file.
    pub fn new(key: String, sensitive: bool) -> TerraformVariableDefinition {
        TerraformVariableDefinition {
            key,
            sensitive,
            default: None,
        }
    }
}
