/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TerraformResponseAllOfTerraformFilesSource {
    #[serde(rename = "git")]
    pub git: Box<models::ApplicationGitRepository>,
}

impl TerraformResponseAllOfTerraformFilesSource {
    pub fn new(git: models::ApplicationGitRepository) -> TerraformResponseAllOfTerraformFilesSource {
        TerraformResponseAllOfTerraformFilesSource {
            git: Box::new(git),
        }
    }
}

