/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TerraformVariablesSourceResponse {
    #[serde(rename = "tf_var_file_paths")]
    pub tf_var_file_paths: Vec<String>,
    /// The input is in json array format: [ [$KEY,$VALUE], [...] ]
    #[serde(rename = "tf_vars")]
    pub tf_vars: Vec<Vec<String>>,
}

impl TerraformVariablesSourceResponse {
    pub fn new(
        tf_var_file_paths: Vec<String>,
        tf_vars: Vec<Vec<String>>,
    ) -> TerraformVariablesSourceResponse {
        TerraformVariablesSourceResponse {
            tf_var_file_paths,
            tf_vars,
        }
    }
}
