/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TfVarsDiscoveryModeAutoDiscover : Automatically discover all tfvars files in the repository
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TfVarsDiscoveryModeAutoDiscover {
    /// Discriminator for auto-discovery mode
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl TfVarsDiscoveryModeAutoDiscover {
    /// Automatically discover all tfvars files in the repository
    pub fn new(r#type: Type) -> TfVarsDiscoveryModeAutoDiscover {
        TfVarsDiscoveryModeAutoDiscover { r#type }
    }
}
/// Discriminator for auto-discovery mode
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "AutoDiscover")]
    AutoDiscover,
}

impl Default for Type {
    fn default() -> Type {
        Self::AutoDiscover
    }
}
