/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSignUpResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(
        rename = "first_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub first_name: Option<Option<String>>,
    #[serde(
        rename = "last_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_name: Option<Option<String>>,
    #[serde(
        rename = "user_email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_email: Option<Option<String>>,
    #[serde(
        rename = "type_of_use",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub type_of_use: Option<Option<String>>,
    #[serde(
        rename = "company_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub company_name: Option<Option<String>>,
    #[serde(
        rename = "company_size",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub company_size: Option<Option<String>>,
    #[serde(
        rename = "user_role",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_role: Option<Option<String>>,
    #[serde(
        rename = "qovery_usage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub qovery_usage: Option<Option<String>>,
    #[serde(
        rename = "qovery_usage_other",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub qovery_usage_other: Option<Option<String>>,
    #[serde(
        rename = "user_questions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_questions: Option<Option<String>>,
    #[serde(
        rename = "dx_auth",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub dx_auth: Option<Option<bool>>,
    #[serde(
        rename = "current_step",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub current_step: Option<Option<String>>,
    #[serde(
        rename = "infrastructure_hosting",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub infrastructure_hosting: Option<Option<String>>,
}

impl UserSignUpResponse {
    pub fn new(id: uuid::Uuid) -> UserSignUpResponse {
        UserSignUpResponse {
            id,
            first_name: None,
            last_name: None,
            user_email: None,
            type_of_use: None,
            company_name: None,
            company_size: None,
            user_role: None,
            qovery_usage: None,
            qovery_usage_other: None,
            user_questions: None,
            dx_auth: None,
            current_step: None,
            infrastructure_hosting: None,
        }
    }
}
