/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariableRequest {
    /// the key of the environment variable
    #[serde(rename = "key")]
    pub key: String,
    /// the value of the environment variable
    #[serde(rename = "value")]
    pub value: String,
    /// the path where the file will be mounted (only if type =file)
    #[serde(
        rename = "mount_path",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mount_path: Option<Option<String>>,
    /// if true, the variable will be considered as a secret and will not be accessible after its creation. Only your applications will be able to access its value at build and run time.
    #[serde(rename = "is_secret")]
    pub is_secret: bool,
    #[serde(rename = "variable_scope")]
    pub variable_scope: models::ApiVariableScopeEnum,
    /// based on the selected scope, it contains the ID of the service, environment or project where the variable is attached
    #[serde(rename = "variable_parent_id")]
    pub variable_parent_id: uuid::Uuid,
    /// optional variable description (255 characters maximum)
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(
        rename = "enable_interpolation_in_file",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_interpolation_in_file: Option<Option<bool>>,
}

impl VariableRequest {
    pub fn new(
        key: String,
        value: String,
        is_secret: bool,
        variable_scope: models::ApiVariableScopeEnum,
        variable_parent_id: uuid::Uuid,
    ) -> VariableRequest {
        VariableRequest {
            key,
            value,
            mount_path: None,
            is_secret,
            variable_scope,
            variable_parent_id,
            description: None,
            enable_interpolation_in_file: None,
        }
    }
}
