/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariableImportRequestVarsInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "scope")]
    pub scope: models::ApiVariableScopeEnum,
    #[serde(rename = "is_secret")]
    pub is_secret: bool,
}

impl VariableImportRequestVarsInner {
    pub fn new(name: String, value: String, scope: models::ApiVariableScopeEnum, is_secret: bool) -> VariableImportRequestVarsInner {
        VariableImportRequestVarsInner {
            name,
            value,
            scope,
            is_secret,
        }
    }
}

