/*
 * Qovery API
 *
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support+api+documentation@qovery.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookEventResponse {
    /// Unique identifier
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Timestamp when the webhook event was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "kind")]
    pub kind: models::OrganizationWebhookKindEnum,
    #[serde(rename = "matched_event")]
    pub matched_event: models::OrganizationWebhookEventEnum,
    /// The webhook target URL that was invoked
    #[serde(rename = "target_url_used")]
    pub target_url_used: String,
    /// The request payload sent to the webhook
    #[serde(rename = "request")]
    pub request: std::collections::HashMap<String, serde_json::Value>,
    /// HTTP status code returned by the webhook target
    #[serde(rename = "target_response_status_code")]
    pub target_response_status_code: i32,
    /// Response body from the webhook target
    #[serde(
        rename = "target_response_body",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub target_response_body: Option<Option<String>>,
}

impl WebhookEventResponse {
    pub fn new(
        id: uuid::Uuid,
        created_at: String,
        kind: models::OrganizationWebhookKindEnum,
        matched_event: models::OrganizationWebhookEventEnum,
        target_url_used: String,
        request: std::collections::HashMap<String, serde_json::Value>,
        target_response_status_code: i32,
    ) -> WebhookEventResponse {
        WebhookEventResponse {
            id,
            created_at,
            kind,
            matched_event,
            target_url_used,
            request,
            target_response_status_code,
            target_response_body: None,
        }
    }
}
